/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.38
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Provides information on the topography of the route or leg, i.e. the total ascent and descent. Elevation‑based metrics represent approximate values and may differ from real‑world measurements.
 * 
 * For each leg the constraint ascent − descent = net elevation difference (last point minus first point) is maintained. Because of this, the sum of ascent or descent values across all legs may slightly exceed the corresponding route total.
 * @export
 * @interface ElevationReport
 */
export interface ElevationReport {
    /**
     * Total ascent of the route or leg [m], estimated from sampled elevation data along the route.
     * @type {number}
     * @memberof ElevationReport
     */
    ascent: number;
    /**
     * Total descent of the route or leg [m], estimated from sampled elevation data along the route.
     * @type {number}
     * @memberof ElevationReport
     */
    descent: number;
}

/**
 * Check if a given object implements the ElevationReport interface.
 */
export function instanceOfElevationReport(value: object): value is ElevationReport {
    if (!('ascent' in value) || value['ascent'] === undefined) return false;
    if (!('descent' in value) || value['descent'] === undefined) return false;
    return true;
}

export function ElevationReportFromJSON(json: any): ElevationReport {
    return ElevationReportFromJSONTyped(json, false);
}

export function ElevationReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElevationReport {
    if (json == null) {
        return json;
    }
    return {
        
        'ascent': json['ascent'],
        'descent': json['descent'],
    };
}

export function ElevationReportToJSON(value?: ElevationReport | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ascent': value['ascent'],
        'descent': value['descent'],
    };
}

