/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LowEmissionZoneApprovals = {
    NONE: 'NONE',
    AT_EURO_1: 'AT_EURO_1',
    AT_EURO_2: 'AT_EURO_2',
    AT_EURO_3: 'AT_EURO_3',
    AT_EURO_4: 'AT_EURO_4',
    AT_EURO_5: 'AT_EURO_5',
    AT_EURO_6: 'AT_EURO_6',
    DE_GREEN: 'DE_GREEN',
    DE_YELLOW: 'DE_YELLOW',
    DE_RED: 'DE_RED',
    DK_AUTHORIZED: 'DK_AUTHORIZED',
    ES_CAT_B: 'ES_CAT_B',
    ES_CAT_C: 'ES_CAT_C',
    ES_CAT_ECO: 'ES_CAT_ECO',
    ES_CAT_ZERO: 'ES_CAT_ZERO',
    FR_CRITAIR_0: 'FR_CRITAIR_0',
    FR_CRITAIR_1: 'FR_CRITAIR_1',
    FR_CRITAIR_2: 'FR_CRITAIR_2',
    FR_CRITAIR_3: 'FR_CRITAIR_3',
    FR_CRITAIR_4: 'FR_CRITAIR_4',
    FR_CRITAIR_5: 'FR_CRITAIR_5'
} as const;
export type LowEmissionZoneApprovals = typeof LowEmissionZoneApprovals[keyof typeof LowEmissionZoneApprovals];


export function instanceOfLowEmissionZoneApprovals(value: any): boolean {
    for (const key in LowEmissionZoneApprovals) {
        if (Object.prototype.hasOwnProperty.call(LowEmissionZoneApprovals, key)) {
            if (LowEmissionZoneApprovals[key as keyof typeof LowEmissionZoneApprovals] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LowEmissionZoneApprovalsFromJSON(json: any): LowEmissionZoneApprovals {
    return LowEmissionZoneApprovalsFromJSONTyped(json, false);
}

export function LowEmissionZoneApprovalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LowEmissionZoneApprovals {
    return json as LowEmissionZoneApprovals;
}

export function LowEmissionZoneApprovalsToJSON(value?: LowEmissionZoneApprovals | null): any {
    return value as any;
}

