/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.37
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpeedByRoadCategory } from './SpeedByRoadCategory';
import {
    SpeedByRoadCategoryFromJSON,
    SpeedByRoadCategoryFromJSONTyped,
    SpeedByRoadCategoryToJSON,
} from './SpeedByRoadCategory';

/**
 * Routing-relevant options which control the route path in detail. These parameters can be specified in addition to those in **options** and will override them.
 * The default values depend on the **profile** and can be retrieved from the Data API.
 * @export
 * @interface RouteOptions
 */
export interface RouteOptions {
    /**
     * The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads
     * will be limited to this value.
     * See [here](./concepts/speeds) for more information.
     * Do not specify **options[maximumSpeed]**, if this parameter is given.
     * @type {number}
     * @memberof RouteOptions
     */
    maximumSpeed?: number;
    /**
     * The speeds used to calculate the driving times by road category. For each road category a minimum and a maximum speed have to be specified.
     * The first array element represents motorways, the last one pedestrian and cycle paths, see [here](../data-api/concepts/road-categories)
     * for more information on road categories.
     * 
     * The speed actually used for a road segment depends on its road category and a speed category defined in the map data
     * and is calculated by linear interpolation between the minimum and maximum speed.
     * 
     * This parameter can be specified only, if **options[trafficMode]** is _AVERAGE_ and neither **options[startTime]** 
     * nor **options[arrivalTime]** is specified. Otherwise, an error will be returned.
     * 
     * See [here](./concepts/speeds) for more information, in particular on the influence of further speed-related parameters
     * such as **options[maximumSpeed]**, **options[speedFactor]** and relative speeds applied by custom road attribute scenarios.
     * @type {Array<SpeedByRoadCategory>}
     * @memberof RouteOptions
     */
    speedsByRoadCategory?: Array<SpeedByRoadCategory>;
    /**
     * Specifies the weighting between travel time and travel distance when calculating a route.
     * The value defines the preference for minimizing travel time over minimizing travel distance.
     * - 0: Route is optimized purely for shortest distance.
     * - 100: Route is optimized purely for shortest travel time.
     * - 1-99: A weighted combination of travel time and distance is applied, with higher values
     *     giving more importance to travel time.
     * 
     * For motorized profiles, values between 80 and 90 typically provide the most realistic and efficient routing behavior
     * whereas values below 30 often produce routes that are not realistically driveable. Such low values
     * are mainly useful for determining theoretical lower bounds on distance rather than for practical
     * route planning.
     * 
     * This parameter will be ignored, if a **routeId** is specified.
     * @type {number}
     * @memberof RouteOptions
     */
    timePreferenceOverDistance?: number;
}

/**
 * Check if a given object implements the RouteOptions interface.
 */
export function instanceOfRouteOptions(value: object): value is RouteOptions {
    return true;
}

export function RouteOptionsFromJSON(json: any): RouteOptions {
    return RouteOptionsFromJSONTyped(json, false);
}

export function RouteOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'maximumSpeed': json['maximumSpeed'] == null ? undefined : json['maximumSpeed'],
        'speedsByRoadCategory': json['speedsByRoadCategory'] == null ? undefined : ((json['speedsByRoadCategory'] as Array<any>).map(SpeedByRoadCategoryFromJSON)),
        'timePreferenceOverDistance': json['timePreferenceOverDistance'] == null ? undefined : json['timePreferenceOverDistance'],
    };
}

export function RouteOptionsToJSON(value?: RouteOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'maximumSpeed': value['maximumSpeed'],
        'speedsByRoadCategory': value['speedsByRoadCategory'] == null ? undefined : ((value['speedsByRoadCategory'] as Array<any>).map(SpeedByRoadCategoryToJSON)),
        'timePreferenceOverDistance': value['timePreferenceOverDistance'],
    };
}

