/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.37
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpeedByRoadCategory
 */
export interface SpeedByRoadCategory {
    /**
     * The minimum speed of the vehicle [km/h] for roads of this road category. Must be less or equal to the maximum speed.
     * @type {number}
     * @memberof SpeedByRoadCategory
     */
    minimumSpeed: number;
    /**
     * The maximum speed of the vehicle [km/h] for roads of this road category. Must be greater or equal to the minimum speed.
     * @type {number}
     * @memberof SpeedByRoadCategory
     */
    maximumSpeed: number;
}

/**
 * Check if a given object implements the SpeedByRoadCategory interface.
 */
export function instanceOfSpeedByRoadCategory(value: object): value is SpeedByRoadCategory {
    if (!('minimumSpeed' in value) || value['minimumSpeed'] === undefined) return false;
    if (!('maximumSpeed' in value) || value['maximumSpeed'] === undefined) return false;
    return true;
}

export function SpeedByRoadCategoryFromJSON(json: any): SpeedByRoadCategory {
    return SpeedByRoadCategoryFromJSONTyped(json, false);
}

export function SpeedByRoadCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeedByRoadCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'minimumSpeed': json['minimumSpeed'],
        'maximumSpeed': json['maximumSpeed'],
    };
}

export function SpeedByRoadCategoryToJSON(value?: SpeedByRoadCategory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'minimumSpeed': value['minimumSpeed'],
        'maximumSpeed': value['maximumSpeed'],
    };
}

