/*
 * Routing
 *
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.38
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routing.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routing.Model
{
    /// <summary>
    /// Provides information on the topography of the route or leg, i.e. the total ascent and descent. Elevation‑based metrics represent approximate values and may differ from real‑world measurements.  For each leg the constraint ascent − descent &#x3D; net elevation difference (last point minus first point) is maintained. Because of this, the sum of ascent or descent values across all legs may slightly exceed the corresponding route total.
    /// </summary>
    [DataContract(Name = "ElevationReport")]
    public partial class ElevationReport : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ElevationReport" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ElevationReport() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ElevationReport" /> class.
        /// </summary>
        /// <param name="ascent">Total ascent of the route or leg [m], estimated from sampled elevation data along the route. (required).</param>
        /// <param name="descent">Total descent of the route or leg [m], estimated from sampled elevation data along the route. (required).</param>
        public ElevationReport(int? ascent = default(int?), int? descent = default(int?))
        {
            // to ensure "ascent" is required (not null)
            if (ascent == null)
            {
                throw new ArgumentNullException("ascent is a required property for ElevationReport and cannot be null");
            }
            this.Ascent = ascent;
            // to ensure "descent" is required (not null)
            if (descent == null)
            {
                throw new ArgumentNullException("descent is a required property for ElevationReport and cannot be null");
            }
            this.Descent = descent;
        }

        /// <summary>
        /// Total ascent of the route or leg [m], estimated from sampled elevation data along the route.
        /// </summary>
        /// <value>Total ascent of the route or leg [m], estimated from sampled elevation data along the route.</value>
        [DataMember(Name = "ascent", IsRequired = true, EmitDefaultValue = true)]
        public int? Ascent { get; set; }

        /// <summary>
        /// Total descent of the route or leg [m], estimated from sampled elevation data along the route.
        /// </summary>
        /// <value>Total descent of the route or leg [m], estimated from sampled elevation data along the route.</value>
        [DataMember(Name = "descent", IsRequired = true, EmitDefaultValue = true)]
        public int? Descent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ElevationReport {\n");
            sb.Append("  Ascent: ").Append(Ascent).Append("\n");
            sb.Append("  Descent: ").Append(Descent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Ascent (int?) minimum
            if (this.Ascent < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Ascent, must be a value greater than or equal to 0.", new [] { "Ascent" });
            }

            // Descent (int?) minimum
            if (this.Descent < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Descent, must be a value greater than or equal to 0.", new [] { "Descent" });
            }

            yield break;
        }
    }

}
