/*
 * Routing
 *
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.36
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routing.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routing.Model
{
    /// <summary>
    /// Defines LowEmissionZoneApprovals
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LowEmissionZoneApprovals
    {
        /// <summary>
        /// Enum NONE for value: NONE
        /// </summary>
        [EnumMember(Value = "NONE")]
        NONE = 1,

        /// <summary>
        /// Enum AT_EURO_1 for value: AT_EURO_1
        /// </summary>
        [EnumMember(Value = "AT_EURO_1")]
        AT_EURO_1 = 2,

        /// <summary>
        /// Enum AT_EURO_2 for value: AT_EURO_2
        /// </summary>
        [EnumMember(Value = "AT_EURO_2")]
        AT_EURO_2 = 3,

        /// <summary>
        /// Enum AT_EURO_3 for value: AT_EURO_3
        /// </summary>
        [EnumMember(Value = "AT_EURO_3")]
        AT_EURO_3 = 4,

        /// <summary>
        /// Enum AT_EURO_4 for value: AT_EURO_4
        /// </summary>
        [EnumMember(Value = "AT_EURO_4")]
        AT_EURO_4 = 5,

        /// <summary>
        /// Enum AT_EURO_5 for value: AT_EURO_5
        /// </summary>
        [EnumMember(Value = "AT_EURO_5")]
        AT_EURO_5 = 6,

        /// <summary>
        /// Enum AT_EURO_6 for value: AT_EURO_6
        /// </summary>
        [EnumMember(Value = "AT_EURO_6")]
        AT_EURO_6 = 7,

        /// <summary>
        /// Enum DE_GREEN for value: DE_GREEN
        /// </summary>
        [EnumMember(Value = "DE_GREEN")]
        DE_GREEN = 8,

        /// <summary>
        /// Enum DE_YELLOW for value: DE_YELLOW
        /// </summary>
        [EnumMember(Value = "DE_YELLOW")]
        DE_YELLOW = 9,

        /// <summary>
        /// Enum DE_RED for value: DE_RED
        /// </summary>
        [EnumMember(Value = "DE_RED")]
        DE_RED = 10,

        /// <summary>
        /// Enum DK_AUTHORIZED for value: DK_AUTHORIZED
        /// </summary>
        [EnumMember(Value = "DK_AUTHORIZED")]
        DK_AUTHORIZED = 11,

        /// <summary>
        /// Enum ES_CAT_B for value: ES_CAT_B
        /// </summary>
        [EnumMember(Value = "ES_CAT_B")]
        ES_CAT_B = 12,

        /// <summary>
        /// Enum ES_CAT_C for value: ES_CAT_C
        /// </summary>
        [EnumMember(Value = "ES_CAT_C")]
        ES_CAT_C = 13,

        /// <summary>
        /// Enum ES_CAT_ECO for value: ES_CAT_ECO
        /// </summary>
        [EnumMember(Value = "ES_CAT_ECO")]
        ES_CAT_ECO = 14,

        /// <summary>
        /// Enum ES_CAT_ZERO for value: ES_CAT_ZERO
        /// </summary>
        [EnumMember(Value = "ES_CAT_ZERO")]
        ES_CAT_ZERO = 15,

        /// <summary>
        /// Enum FR_CRITAIR_0 for value: FR_CRITAIR_0
        /// </summary>
        [EnumMember(Value = "FR_CRITAIR_0")]
        FR_CRITAIR_0 = 16,

        /// <summary>
        /// Enum FR_CRITAIR_1 for value: FR_CRITAIR_1
        /// </summary>
        [EnumMember(Value = "FR_CRITAIR_1")]
        FR_CRITAIR_1 = 17,

        /// <summary>
        /// Enum FR_CRITAIR_2 for value: FR_CRITAIR_2
        /// </summary>
        [EnumMember(Value = "FR_CRITAIR_2")]
        FR_CRITAIR_2 = 18,

        /// <summary>
        /// Enum FR_CRITAIR_3 for value: FR_CRITAIR_3
        /// </summary>
        [EnumMember(Value = "FR_CRITAIR_3")]
        FR_CRITAIR_3 = 19,

        /// <summary>
        /// Enum FR_CRITAIR_4 for value: FR_CRITAIR_4
        /// </summary>
        [EnumMember(Value = "FR_CRITAIR_4")]
        FR_CRITAIR_4 = 20,

        /// <summary>
        /// Enum FR_CRITAIR_5 for value: FR_CRITAIR_5
        /// </summary>
        [EnumMember(Value = "FR_CRITAIR_5")]
        FR_CRITAIR_5 = 21
    }

}
