/*
 * Routing
 *
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.36
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routing.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routing.Model
{
    /// <summary>
    /// Defines LowEmissionZoneExemptions
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LowEmissionZoneExemptions
    {
        /// <summary>
        /// Enum BE_LAGE_EMISSIEZONE_ANTWERPEN for value: BE_LAGE_EMISSIEZONE_ANTWERPEN
        /// </summary>
        [EnumMember(Value = "BE_LAGE_EMISSIEZONE_ANTWERPEN")]
        BE_LAGE_EMISSIEZONE_ANTWERPEN = 1,

        /// <summary>
        /// Enum BE_LAGE_EMISSIEZONE_GENT for value: BE_LAGE_EMISSIEZONE_GENT
        /// </summary>
        [EnumMember(Value = "BE_LAGE_EMISSIEZONE_GENT")]
        BE_LAGE_EMISSIEZONE_GENT = 2,

        /// <summary>
        /// Enum BE_ZONE_BASSE_EMISSION_BRUXELLES for value: BE_ZONE_BASSE_EMISSION_BRUXELLES
        /// </summary>
        [EnumMember(Value = "BE_ZONE_BASSE_EMISSION_BRUXELLES")]
        BE_ZONE_BASSE_EMISSION_BRUXELLES = 3,

        /// <summary>
        /// Enum DK_AALBORG_MILJOZONE for value: DK_AALBORG_MILJOZONE
        /// </summary>
        [EnumMember(Value = "DK_AALBORG_MILJOZONE")]
        DK_AALBORG_MILJOZONE = 4,

        /// <summary>
        /// Enum DK_ARHUS_MILJOZONE for value: DK_ARHUS_MILJOZONE
        /// </summary>
        [EnumMember(Value = "DK_ARHUS_MILJOZONE")]
        DK_ARHUS_MILJOZONE = 5,

        /// <summary>
        /// Enum DK_FREDERIKSBERG_MILJOZONE for value: DK_FREDERIKSBERG_MILJOZONE
        /// </summary>
        [EnumMember(Value = "DK_FREDERIKSBERG_MILJOZONE")]
        DK_FREDERIKSBERG_MILJOZONE = 6,

        /// <summary>
        /// Enum DK_KOBENHAVN_MILJOZONE for value: DK_KOBENHAVN_MILJOZONE
        /// </summary>
        [EnumMember(Value = "DK_KOBENHAVN_MILJOZONE")]
        DK_KOBENHAVN_MILJOZONE = 7,

        /// <summary>
        /// Enum DK_ODENSE_MILJOZONE for value: DK_ODENSE_MILJOZONE
        /// </summary>
        [EnumMember(Value = "DK_ODENSE_MILJOZONE")]
        DK_ODENSE_MILJOZONE = 8,

        /// <summary>
        /// Enum ES_ZBE_ALMERIA for value: ES_ZBE_ALMERIA
        /// </summary>
        [EnumMember(Value = "ES_ZBE_ALMERIA")]
        ES_ZBE_ALMERIA = 9,

        /// <summary>
        /// Enum ES_ZBE_BILBAO for value: ES_ZBE_BILBAO
        /// </summary>
        [EnumMember(Value = "ES_ZBE_BILBAO")]
        ES_ZBE_BILBAO = 10,

        /// <summary>
        /// Enum ES_ZBE_CORDOBA for value: ES_ZBE_CORDOBA
        /// </summary>
        [EnumMember(Value = "ES_ZBE_CORDOBA")]
        ES_ZBE_CORDOBA = 11,

        /// <summary>
        /// Enum ES_ZBE_SAN_SEBASTIAN for value: ES_ZBE_SAN_SEBASTIAN
        /// </summary>
        [EnumMember(Value = "ES_ZBE_SAN_SEBASTIAN")]
        ES_ZBE_SAN_SEBASTIAN = 12,

        /// <summary>
        /// Enum ES_ZBE_TORREMOLINOS for value: ES_ZBE_TORREMOLINOS
        /// </summary>
        [EnumMember(Value = "ES_ZBE_TORREMOLINOS")]
        ES_ZBE_TORREMOLINOS = 13,

        /// <summary>
        /// Enum ES_ZBE_VALLADOLID for value: ES_ZBE_VALLADOLID
        /// </summary>
        [EnumMember(Value = "ES_ZBE_VALLADOLID")]
        ES_ZBE_VALLADOLID = 14,

        /// <summary>
        /// Enum FR_STRASBOURG_ZFE for value: FR_STRASBOURG_ZFE
        /// </summary>
        [EnumMember(Value = "FR_STRASBOURG_ZFE")]
        FR_STRASBOURG_ZFE = 15,

        /// <summary>
        /// Enum GB_ABERDEEN_LEZ for value: GB_ABERDEEN_LEZ
        /// </summary>
        [EnumMember(Value = "GB_ABERDEEN_LEZ")]
        GB_ABERDEEN_LEZ = 16,

        /// <summary>
        /// Enum GB_BATH_CAZ for value: GB_BATH_CAZ
        /// </summary>
        [EnumMember(Value = "GB_BATH_CAZ")]
        GB_BATH_CAZ = 17,

        /// <summary>
        /// Enum GB_BIRMINGHAM_CAZ for value: GB_BIRMINGHAM_CAZ
        /// </summary>
        [EnumMember(Value = "GB_BIRMINGHAM_CAZ")]
        GB_BIRMINGHAM_CAZ = 18,

        /// <summary>
        /// Enum GB_BRADFORD_CAZ for value: GB_BRADFORD_CAZ
        /// </summary>
        [EnumMember(Value = "GB_BRADFORD_CAZ")]
        GB_BRADFORD_CAZ = 19,

        /// <summary>
        /// Enum GB_BRISTOL_CAZ for value: GB_BRISTOL_CAZ
        /// </summary>
        [EnumMember(Value = "GB_BRISTOL_CAZ")]
        GB_BRISTOL_CAZ = 20,

        /// <summary>
        /// Enum GB_DUNDEE_LEZ for value: GB_DUNDEE_LEZ
        /// </summary>
        [EnumMember(Value = "GB_DUNDEE_LEZ")]
        GB_DUNDEE_LEZ = 21,

        /// <summary>
        /// Enum GB_EDINBURGH_LEZ for value: GB_EDINBURGH_LEZ
        /// </summary>
        [EnumMember(Value = "GB_EDINBURGH_LEZ")]
        GB_EDINBURGH_LEZ = 22,

        /// <summary>
        /// Enum GB_GLASGOW_LEZ for value: GB_GLASGOW_LEZ
        /// </summary>
        [EnumMember(Value = "GB_GLASGOW_LEZ")]
        GB_GLASGOW_LEZ = 23,

        /// <summary>
        /// Enum GB_LONDON_ULTRA_LOW_EMISSION_ZONE for value: GB_LONDON_ULTRA_LOW_EMISSION_ZONE
        /// </summary>
        [EnumMember(Value = "GB_LONDON_ULTRA_LOW_EMISSION_ZONE")]
        GB_LONDON_ULTRA_LOW_EMISSION_ZONE = 24,

        /// <summary>
        /// Enum GB_NEWCASTLE_CAZ for value: GB_NEWCASTLE_CAZ
        /// </summary>
        [EnumMember(Value = "GB_NEWCASTLE_CAZ")]
        GB_NEWCASTLE_CAZ = 25,

        /// <summary>
        /// Enum GB_PORTSMOUTH_CAZ for value: GB_PORTSMOUTH_CAZ
        /// </summary>
        [EnumMember(Value = "GB_PORTSMOUTH_CAZ")]
        GB_PORTSMOUTH_CAZ = 26,

        /// <summary>
        /// Enum GB_SHEFFIELD_CAZ for value: GB_SHEFFIELD_CAZ
        /// </summary>
        [EnumMember(Value = "GB_SHEFFIELD_CAZ")]
        GB_SHEFFIELD_CAZ = 27,

        /// <summary>
        /// Enum IT_MILANO_AREA_C for value: IT_MILANO_AREA_C
        /// </summary>
        [EnumMember(Value = "IT_MILANO_AREA_C")]
        IT_MILANO_AREA_C = 28,

        /// <summary>
        /// Enum IT_PALERMO_ZTL for value: IT_PALERMO_ZTL
        /// </summary>
        [EnumMember(Value = "IT_PALERMO_ZTL")]
        IT_PALERMO_ZTL = 29,

        /// <summary>
        /// Enum NL_AMSTERDAM_MILIEUZONE for value: NL_AMSTERDAM_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_AMSTERDAM_MILIEUZONE")]
        NL_AMSTERDAM_MILIEUZONE = 30,

        /// <summary>
        /// Enum NL_AMSTERDAM_ZERO_EMISSIEZONE for value: NL_AMSTERDAM_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_AMSTERDAM_ZERO_EMISSIEZONE")]
        NL_AMSTERDAM_ZERO_EMISSIEZONE = 31,

        /// <summary>
        /// Enum NL_ARNHEM_MILIEUZONE for value: NL_ARNHEM_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_ARNHEM_MILIEUZONE")]
        NL_ARNHEM_MILIEUZONE = 32,

        /// <summary>
        /// Enum NL_ASSEN_ZERO_EMISSIEZONE for value: NL_ASSEN_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_ASSEN_ZERO_EMISSIEZONE")]
        NL_ASSEN_ZERO_EMISSIEZONE = 33,

        /// <summary>
        /// Enum NL_BREDA_MILIEUZONE for value: NL_BREDA_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_BREDA_MILIEUZONE")]
        NL_BREDA_MILIEUZONE = 34,

        /// <summary>
        /// Enum NL_DELFT_HAAG_ZERO_EMISSIEZONE for value: NL_DELFT_HAAG_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_DELFT_HAAG_ZERO_EMISSIEZONE")]
        NL_DELFT_HAAG_ZERO_EMISSIEZONE = 35,

        /// <summary>
        /// Enum NL_DELFT_MILIEUZONE for value: NL_DELFT_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_DELFT_MILIEUZONE")]
        NL_DELFT_MILIEUZONE = 36,

        /// <summary>
        /// Enum NL_DEN_HAAG_MILIEUZONE for value: NL_DEN_HAAG_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_DEN_HAAG_MILIEUZONE")]
        NL_DEN_HAAG_MILIEUZONE = 37,

        /// <summary>
        /// Enum NL_DEN_HAAG_ZERO_EMISSIEZONE for value: NL_DEN_HAAG_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_DEN_HAAG_ZERO_EMISSIEZONE")]
        NL_DEN_HAAG_ZERO_EMISSIEZONE = 38,

        /// <summary>
        /// Enum NL_EINDHOVEN_MILIEUZONE for value: NL_EINDHOVEN_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_EINDHOVEN_MILIEUZONE")]
        NL_EINDHOVEN_MILIEUZONE = 39,

        /// <summary>
        /// Enum NL_EINDHOVEN_ZERO_EMISSIEZONE for value: NL_EINDHOVEN_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_EINDHOVEN_ZERO_EMISSIEZONE")]
        NL_EINDHOVEN_ZERO_EMISSIEZONE = 40,

        /// <summary>
        /// Enum NL_GOUDA_ZERO_EMISSIEZONE for value: NL_GOUDA_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_GOUDA_ZERO_EMISSIEZONE")]
        NL_GOUDA_ZERO_EMISSIEZONE = 41,

        /// <summary>
        /// Enum NL_HAARLEM_MILIEUZONE for value: NL_HAARLEM_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_HAARLEM_MILIEUZONE")]
        NL_HAARLEM_MILIEUZONE = 42,

        /// <summary>
        /// Enum NL_LEIDEN_MILIEUZONE for value: NL_LEIDEN_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_LEIDEN_MILIEUZONE")]
        NL_LEIDEN_MILIEUZONE = 43,

        /// <summary>
        /// Enum NL_LEIDEN_ZERO_EMISSIEZONE for value: NL_LEIDEN_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_LEIDEN_ZERO_EMISSIEZONE")]
        NL_LEIDEN_ZERO_EMISSIEZONE = 44,

        /// <summary>
        /// Enum NL_MAASTRICHT_MILIEUZONE for value: NL_MAASTRICHT_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_MAASTRICHT_MILIEUZONE")]
        NL_MAASTRICHT_MILIEUZONE = 45,

        /// <summary>
        /// Enum NL_MAASTRICHT_ZERO_EMISSIEZONE for value: NL_MAASTRICHT_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_MAASTRICHT_ZERO_EMISSIEZONE")]
        NL_MAASTRICHT_ZERO_EMISSIEZONE = 46,

        /// <summary>
        /// Enum NL_MAASVLAKTE_ROTTERDAM_MILIEUZONE for value: NL_MAASVLAKTE_ROTTERDAM_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_MAASVLAKTE_ROTTERDAM_MILIEUZONE")]
        NL_MAASVLAKTE_ROTTERDAM_MILIEUZONE = 47,

        /// <summary>
        /// Enum NL_NIJMEGEN_ZERO_EMISSIEZONE for value: NL_NIJMEGEN_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_NIJMEGEN_ZERO_EMISSIEZONE")]
        NL_NIJMEGEN_ZERO_EMISSIEZONE = 48,

        /// <summary>
        /// Enum NL_RIJSWIJK_MILIEUZONE for value: NL_RIJSWIJK_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_RIJSWIJK_MILIEUZONE")]
        NL_RIJSWIJK_MILIEUZONE = 49,

        /// <summary>
        /// Enum NL_ROTTERDAM_MILIEUZONE for value: NL_ROTTERDAM_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_ROTTERDAM_MILIEUZONE")]
        NL_ROTTERDAM_MILIEUZONE = 50,

        /// <summary>
        /// Enum NL_ROTTERDAM_ZERO_EMISSIEZONE for value: NL_ROTTERDAM_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_ROTTERDAM_ZERO_EMISSIEZONE")]
        NL_ROTTERDAM_ZERO_EMISSIEZONE = 51,

        /// <summary>
        /// Enum NL_S_GRAVENDIJKWAL_MILIEUZONE for value: NL_S_GRAVENDIJKWAL_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_S_GRAVENDIJKWAL_MILIEUZONE")]
        NL_S_GRAVENDIJKWAL_MILIEUZONE = 52,

        /// <summary>
        /// Enum NL_S_HERTOGENBOSCH_MILIEUZONE for value: NL_S_HERTOGENBOSCH_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_S_HERTOGENBOSCH_MILIEUZONE")]
        NL_S_HERTOGENBOSCH_MILIEUZONE = 53,

        /// <summary>
        /// Enum NL_TILBURG_MILIEUZONE for value: NL_TILBURG_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_TILBURG_MILIEUZONE")]
        NL_TILBURG_MILIEUZONE = 54,

        /// <summary>
        /// Enum NL_TILBURG_ZERO_EMISSIEZONE for value: NL_TILBURG_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_TILBURG_ZERO_EMISSIEZONE")]
        NL_TILBURG_ZERO_EMISSIEZONE = 55,

        /// <summary>
        /// Enum NL_UTRECHT_MILIEUZONE for value: NL_UTRECHT_MILIEUZONE
        /// </summary>
        [EnumMember(Value = "NL_UTRECHT_MILIEUZONE")]
        NL_UTRECHT_MILIEUZONE = 56,

        /// <summary>
        /// Enum NL_UTRECHT_ZERO_EMISSIEZONE for value: NL_UTRECHT_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_UTRECHT_ZERO_EMISSIEZONE")]
        NL_UTRECHT_ZERO_EMISSIEZONE = 57,

        /// <summary>
        /// Enum NL_ZWOLLE_ZERO_EMISSIEZONE for value: NL_ZWOLLE_ZERO_EMISSIEZONE
        /// </summary>
        [EnumMember(Value = "NL_ZWOLLE_ZERO_EMISSIEZONE")]
        NL_ZWOLLE_ZERO_EMISSIEZONE = 58
    }

}
