/*
 * Routing
 *
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.37
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routing.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routing.Model
{
    /// <summary>
    /// Routing-relevant options which control the route path in detail. These parameters can be specified in addition to those in **options** and will override them. The default values depend on the **profile** and can be retrieved from the Data API.
    /// </summary>
    [DataContract(Name = "RouteOptions")]
    public partial class RouteOptions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptions" /> class.
        /// </summary>
        /// <param name="maximumSpeed">The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads will be limited to this value. See [here](./concepts/speeds) for more information. Do not specify **options[maximumSpeed]**, if this parameter is given..</param>
        /// <param name="speedsByRoadCategory">The speeds used to calculate the driving times by road category. For each road category a minimum and a maximum speed have to be specified. The first array element represents motorways, the last one pedestrian and cycle paths, see [here](../data-api/concepts/road-categories) for more information on road categories.  The speed actually used for a road segment depends on its road category and a speed category defined in the map data and is calculated by linear interpolation between the minimum and maximum speed.  This parameter can be specified only, if **options[trafficMode]** is _AVERAGE_ and neither **options[startTime]**  nor **options[arrivalTime]** is specified. Otherwise, an error will be returned.  See [here](./concepts/speeds) for more information, in particular on the influence of further speed-related parameters such as **options[maximumSpeed]**, **options[speedFactor]** and relative speeds applied by custom road attribute scenarios..</param>
        /// <param name="timePreferenceOverDistance">Specifies the weighting between travel time and travel distance when calculating a route. The value defines the preference for minimizing travel time over minimizing travel distance. - 0: Route is optimized purely for shortest distance. - 100: Route is optimized purely for shortest travel time. - 1-99: A weighted combination of travel time and distance is applied, with higher values     giving more importance to travel time.  For motorized profiles, values between 80 and 90 typically provide the most realistic and efficient routing behavior whereas values below 30 often produce routes that are not realistically driveable. Such low values are mainly useful for determining theoretical lower bounds on distance rather than for practical route planning.  This parameter will be ignored, if a **routeId** is specified..</param>
        public RouteOptions(int? maximumSpeed = default(int?), List<SpeedByRoadCategory> speedsByRoadCategory = default(List<SpeedByRoadCategory>), int? timePreferenceOverDistance = default(int?))
        {
            this.MaximumSpeed = maximumSpeed;
            this.SpeedsByRoadCategory = speedsByRoadCategory;
            this.TimePreferenceOverDistance = timePreferenceOverDistance;
        }

        /// <summary>
        /// The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads will be limited to this value. See [here](./concepts/speeds) for more information. Do not specify **options[maximumSpeed]**, if this parameter is given.
        /// </summary>
        /// <value>The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads will be limited to this value. See [here](./concepts/speeds) for more information. Do not specify **options[maximumSpeed]**, if this parameter is given.</value>
        [DataMember(Name = "maximumSpeed", EmitDefaultValue = true)]
        public int? MaximumSpeed { get; set; }

        /// <summary>
        /// The speeds used to calculate the driving times by road category. For each road category a minimum and a maximum speed have to be specified. The first array element represents motorways, the last one pedestrian and cycle paths, see [here](../data-api/concepts/road-categories) for more information on road categories.  The speed actually used for a road segment depends on its road category and a speed category defined in the map data and is calculated by linear interpolation between the minimum and maximum speed.  This parameter can be specified only, if **options[trafficMode]** is _AVERAGE_ and neither **options[startTime]**  nor **options[arrivalTime]** is specified. Otherwise, an error will be returned.  See [here](./concepts/speeds) for more information, in particular on the influence of further speed-related parameters such as **options[maximumSpeed]**, **options[speedFactor]** and relative speeds applied by custom road attribute scenarios.
        /// </summary>
        /// <value>The speeds used to calculate the driving times by road category. For each road category a minimum and a maximum speed have to be specified. The first array element represents motorways, the last one pedestrian and cycle paths, see [here](../data-api/concepts/road-categories) for more information on road categories.  The speed actually used for a road segment depends on its road category and a speed category defined in the map data and is calculated by linear interpolation between the minimum and maximum speed.  This parameter can be specified only, if **options[trafficMode]** is _AVERAGE_ and neither **options[startTime]**  nor **options[arrivalTime]** is specified. Otherwise, an error will be returned.  See [here](./concepts/speeds) for more information, in particular on the influence of further speed-related parameters such as **options[maximumSpeed]**, **options[speedFactor]** and relative speeds applied by custom road attribute scenarios.</value>
        [DataMember(Name = "speedsByRoadCategory", EmitDefaultValue = false)]
        public List<SpeedByRoadCategory> SpeedsByRoadCategory { get; set; }

        /// <summary>
        /// Specifies the weighting between travel time and travel distance when calculating a route. The value defines the preference for minimizing travel time over minimizing travel distance. - 0: Route is optimized purely for shortest distance. - 100: Route is optimized purely for shortest travel time. - 1-99: A weighted combination of travel time and distance is applied, with higher values     giving more importance to travel time.  For motorized profiles, values between 80 and 90 typically provide the most realistic and efficient routing behavior whereas values below 30 often produce routes that are not realistically driveable. Such low values are mainly useful for determining theoretical lower bounds on distance rather than for practical route planning.  This parameter will be ignored, if a **routeId** is specified.
        /// </summary>
        /// <value>Specifies the weighting between travel time and travel distance when calculating a route. The value defines the preference for minimizing travel time over minimizing travel distance. - 0: Route is optimized purely for shortest distance. - 100: Route is optimized purely for shortest travel time. - 1-99: A weighted combination of travel time and distance is applied, with higher values     giving more importance to travel time.  For motorized profiles, values between 80 and 90 typically provide the most realistic and efficient routing behavior whereas values below 30 often produce routes that are not realistically driveable. Such low values are mainly useful for determining theoretical lower bounds on distance rather than for practical route planning.  This parameter will be ignored, if a **routeId** is specified.</value>
        [DataMember(Name = "timePreferenceOverDistance", EmitDefaultValue = true)]
        public int? TimePreferenceOverDistance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptions {\n");
            sb.Append("  MaximumSpeed: ").Append(MaximumSpeed).Append("\n");
            sb.Append("  SpeedsByRoadCategory: ").Append(SpeedsByRoadCategory).Append("\n");
            sb.Append("  TimePreferenceOverDistance: ").Append(TimePreferenceOverDistance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaximumSpeed (int?) minimum
            if (this.MaximumSpeed < (int?)1)
            {
                yield return new ValidationResult("Invalid value for MaximumSpeed, must be a value greater than or equal to 1.", new [] { "MaximumSpeed" });
            }

            // TimePreferenceOverDistance (int?) maximum
            if (this.TimePreferenceOverDistance > (int?)100)
            {
                yield return new ValidationResult("Invalid value for TimePreferenceOverDistance, must be a value less than or equal to 100.", new [] { "TimePreferenceOverDistance" });
            }

            // TimePreferenceOverDistance (int?) minimum
            if (this.TimePreferenceOverDistance < (int?)0)
            {
                yield return new ValidationResult("Invalid value for TimePreferenceOverDistance, must be a value greater than or equal to 0.", new [] { "TimePreferenceOverDistance" });
            }

            yield break;
        }
    }

}
