/*
 * Routing
 *
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.37
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routing.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routing.Model
{
    /// <summary>
    /// SpeedByRoadCategory
    /// </summary>
    [DataContract(Name = "SpeedByRoadCategory")]
    public partial class SpeedByRoadCategory : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpeedByRoadCategory" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SpeedByRoadCategory() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SpeedByRoadCategory" /> class.
        /// </summary>
        /// <param name="minimumSpeed">The minimum speed of the vehicle [km/h] for roads of this road category. Must be less or equal to the maximum speed. (required).</param>
        /// <param name="maximumSpeed">The maximum speed of the vehicle [km/h] for roads of this road category. Must be greater or equal to the minimum speed. (required).</param>
        public SpeedByRoadCategory(int? minimumSpeed = default(int?), int? maximumSpeed = default(int?))
        {
            // to ensure "minimumSpeed" is required (not null)
            if (minimumSpeed == null)
            {
                throw new ArgumentNullException("minimumSpeed is a required property for SpeedByRoadCategory and cannot be null");
            }
            this.MinimumSpeed = minimumSpeed;
            // to ensure "maximumSpeed" is required (not null)
            if (maximumSpeed == null)
            {
                throw new ArgumentNullException("maximumSpeed is a required property for SpeedByRoadCategory and cannot be null");
            }
            this.MaximumSpeed = maximumSpeed;
        }

        /// <summary>
        /// The minimum speed of the vehicle [km/h] for roads of this road category. Must be less or equal to the maximum speed.
        /// </summary>
        /// <value>The minimum speed of the vehicle [km/h] for roads of this road category. Must be less or equal to the maximum speed.</value>
        [DataMember(Name = "minimumSpeed", IsRequired = true, EmitDefaultValue = true)]
        public int? MinimumSpeed { get; set; }

        /// <summary>
        /// The maximum speed of the vehicle [km/h] for roads of this road category. Must be greater or equal to the minimum speed.
        /// </summary>
        /// <value>The maximum speed of the vehicle [km/h] for roads of this road category. Must be greater or equal to the minimum speed.</value>
        [DataMember(Name = "maximumSpeed", IsRequired = true, EmitDefaultValue = true)]
        public int? MaximumSpeed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpeedByRoadCategory {\n");
            sb.Append("  MinimumSpeed: ").Append(MinimumSpeed).Append("\n");
            sb.Append("  MaximumSpeed: ").Append(MaximumSpeed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MinimumSpeed (int?) maximum
            if (this.MinimumSpeed > (int?)255)
            {
                yield return new ValidationResult("Invalid value for MinimumSpeed, must be a value less than or equal to 255.", new [] { "MinimumSpeed" });
            }

            // MinimumSpeed (int?) minimum
            if (this.MinimumSpeed < (int?)1)
            {
                yield return new ValidationResult("Invalid value for MinimumSpeed, must be a value greater than or equal to 1.", new [] { "MinimumSpeed" });
            }

            // MaximumSpeed (int?) maximum
            if (this.MaximumSpeed > (int?)255)
            {
                yield return new ValidationResult("Invalid value for MaximumSpeed, must be a value less than or equal to 255.", new [] { "MaximumSpeed" });
            }

            // MaximumSpeed (int?) minimum
            if (this.MaximumSpeed < (int?)1)
            {
                yield return new ValidationResult("Invalid value for MaximumSpeed, must be a value greater than or equal to 1.", new [] { "MaximumSpeed" });
            }

            yield break;
        }
    }

}
