/*
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.38
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routing.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.routing.ApiClient;
/**
 * Provides information on the topography of the route or leg, i.e. the total ascent and descent. Elevation‑based metrics represent approximate values and may differ from real‑world measurements.  For each leg the constraint ascent − descent &#x3D; net elevation difference (last point minus first point) is maintained. Because of this, the sum of ascent or descent values across all legs may slightly exceed the corresponding route total.
 */
@JsonPropertyOrder({
  ElevationReport.JSON_PROPERTY_ASCENT,
  ElevationReport.JSON_PROPERTY_DESCENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-11T12:02:42.197864074Z[Etc/UTC]", comments = "Generator version: 7.8.0")
public class ElevationReport {
  public static final String JSON_PROPERTY_ASCENT = "ascent";
  private Integer ascent;

  public static final String JSON_PROPERTY_DESCENT = "descent";
  private Integer descent;

  public ElevationReport() { 
  }

  public ElevationReport ascent(Integer ascent) {
    this.ascent = ascent;
    return this;
  }

  /**
   * Total ascent of the route or leg [m], estimated from sampled elevation data along the route.
   * minimum: 0
   * @return ascent
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASCENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAscent() {
    return ascent;
  }


  @JsonProperty(JSON_PROPERTY_ASCENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAscent(Integer ascent) {
    this.ascent = ascent;
  }


  public ElevationReport descent(Integer descent) {
    this.descent = descent;
    return this;
  }

  /**
   * Total descent of the route or leg [m], estimated from sampled elevation data along the route.
   * minimum: 0
   * @return descent
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDescent() {
    return descent;
  }


  @JsonProperty(JSON_PROPERTY_DESCENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescent(Integer descent) {
    this.descent = descent;
  }


  /**
   * Return true if this ElevationReport object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElevationReport elevationReport = (ElevationReport) o;
    return Objects.equals(this.ascent, elevationReport.ascent) &&
        Objects.equals(this.descent, elevationReport.descent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ascent, descent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElevationReport {\n");
    sb.append("    ascent: ").append(toIndentedString(ascent)).append("\n");
    sb.append("    descent: ").append(toIndentedString(descent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ascent` to the URL query string
    if (getAscent() != null) {
      joiner.add(String.format("%sascent%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAscent()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `descent` to the URL query string
    if (getDescent() != null) {
      joiner.add(String.format("%sdescent%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDescent()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

