/*
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.37
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routing.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.routing.model.SpeedByRoadCategory;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.routing.ApiClient;
/**
 * Routing-relevant options which control the route path in detail. These parameters can be specified in addition to those in **options** and will override them. The default values depend on the **profile** and can be retrieved from the Data API.
 */
@JsonPropertyOrder({
  RouteOptions.JSON_PROPERTY_MAXIMUM_SPEED,
  RouteOptions.JSON_PROPERTY_SPEEDS_BY_ROAD_CATEGORY,
  RouteOptions.JSON_PROPERTY_TIME_PREFERENCE_OVER_DISTANCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-06T07:43:01.486888480Z[Etc/UTC]", comments = "Generator version: 7.8.0")
public class RouteOptions {
  public static final String JSON_PROPERTY_MAXIMUM_SPEED = "maximumSpeed";
  private Integer maximumSpeed;

  public static final String JSON_PROPERTY_SPEEDS_BY_ROAD_CATEGORY = "speedsByRoadCategory";
  private List<SpeedByRoadCategory> speedsByRoadCategory;

  public static final String JSON_PROPERTY_TIME_PREFERENCE_OVER_DISTANCE = "timePreferenceOverDistance";
  private Integer timePreferenceOverDistance;

  public RouteOptions() { 
  }

  public RouteOptions maximumSpeed(Integer maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
    return this;
  }

  /**
   * The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads will be limited to this value. See [here](./concepts/speeds) for more information. Do not specify **options[maximumSpeed]**, if this parameter is given.
   * minimum: 1
   * @return maximumSpeed
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAXIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaximumSpeed() {
    return maximumSpeed;
  }


  @JsonProperty(JSON_PROPERTY_MAXIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaximumSpeed(Integer maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
  }


  public RouteOptions speedsByRoadCategory(List<SpeedByRoadCategory> speedsByRoadCategory) {
    this.speedsByRoadCategory = speedsByRoadCategory;
    return this;
  }

  public RouteOptions addSpeedsByRoadCategoryItem(SpeedByRoadCategory speedsByRoadCategoryItem) {
    if (this.speedsByRoadCategory == null) {
      this.speedsByRoadCategory = new ArrayList<>();
    }
    this.speedsByRoadCategory.add(speedsByRoadCategoryItem);
    return this;
  }

  /**
   * The speeds used to calculate the driving times by road category. For each road category a minimum and a maximum speed have to be specified. The first array element represents motorways, the last one pedestrian and cycle paths, see [here](../data-api/concepts/road-categories) for more information on road categories.  The speed actually used for a road segment depends on its road category and a speed category defined in the map data and is calculated by linear interpolation between the minimum and maximum speed.  This parameter can be specified only, if **options[trafficMode]** is _AVERAGE_ and neither **options[startTime]**  nor **options[arrivalTime]** is specified. Otherwise, an error will be returned.  See [here](./concepts/speeds) for more information, in particular on the influence of further speed-related parameters such as **options[maximumSpeed]**, **options[speedFactor]** and relative speeds applied by custom road attribute scenarios.
   * @return speedsByRoadCategory
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPEEDS_BY_ROAD_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SpeedByRoadCategory> getSpeedsByRoadCategory() {
    return speedsByRoadCategory;
  }


  @JsonProperty(JSON_PROPERTY_SPEEDS_BY_ROAD_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpeedsByRoadCategory(List<SpeedByRoadCategory> speedsByRoadCategory) {
    this.speedsByRoadCategory = speedsByRoadCategory;
  }


  public RouteOptions timePreferenceOverDistance(Integer timePreferenceOverDistance) {
    this.timePreferenceOverDistance = timePreferenceOverDistance;
    return this;
  }

  /**
   * Specifies the weighting between travel time and travel distance when calculating a route. The value defines the preference for minimizing travel time over minimizing travel distance. - 0: Route is optimized purely for shortest distance. - 100: Route is optimized purely for shortest travel time. - 1-99: A weighted combination of travel time and distance is applied, with higher values     giving more importance to travel time.  For motorized profiles, values between 80 and 90 typically provide the most realistic and efficient routing behavior whereas values below 30 often produce routes that are not realistically driveable. Such low values are mainly useful for determining theoretical lower bounds on distance rather than for practical route planning.  This parameter will be ignored, if a **routeId** is specified.
   * minimum: 0
   * maximum: 100
   * @return timePreferenceOverDistance
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_PREFERENCE_OVER_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTimePreferenceOverDistance() {
    return timePreferenceOverDistance;
  }


  @JsonProperty(JSON_PROPERTY_TIME_PREFERENCE_OVER_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimePreferenceOverDistance(Integer timePreferenceOverDistance) {
    this.timePreferenceOverDistance = timePreferenceOverDistance;
  }


  /**
   * Return true if this RouteOptions object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteOptions routeOptions = (RouteOptions) o;
    return Objects.equals(this.maximumSpeed, routeOptions.maximumSpeed) &&
        Objects.equals(this.speedsByRoadCategory, routeOptions.speedsByRoadCategory) &&
        Objects.equals(this.timePreferenceOverDistance, routeOptions.timePreferenceOverDistance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maximumSpeed, speedsByRoadCategory, timePreferenceOverDistance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteOptions {\n");
    sb.append("    maximumSpeed: ").append(toIndentedString(maximumSpeed)).append("\n");
    sb.append("    speedsByRoadCategory: ").append(toIndentedString(speedsByRoadCategory)).append("\n");
    sb.append("    timePreferenceOverDistance: ").append(toIndentedString(timePreferenceOverDistance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `maximumSpeed` to the URL query string
    if (getMaximumSpeed() != null) {
      joiner.add(String.format("%smaximumSpeed%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMaximumSpeed()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `speedsByRoadCategory` to the URL query string
    if (getSpeedsByRoadCategory() != null) {
      for (int i = 0; i < getSpeedsByRoadCategory().size(); i++) {
        if (getSpeedsByRoadCategory().get(i) != null) {
          joiner.add(getSpeedsByRoadCategory().get(i).toUrlQueryString(String.format("%sspeedsByRoadCategory%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `timePreferenceOverDistance` to the URL query string
    if (getTimePreferenceOverDistance() != null) {
      joiner.add(String.format("%stimePreferenceOverDistance%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTimePreferenceOverDistance()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

