/*
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.37
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routing.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.routing.ApiClient;
/**
 * SpeedByRoadCategory
 */
@JsonPropertyOrder({
  SpeedByRoadCategory.JSON_PROPERTY_MINIMUM_SPEED,
  SpeedByRoadCategory.JSON_PROPERTY_MAXIMUM_SPEED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-06T07:43:01.486888480Z[Etc/UTC]", comments = "Generator version: 7.8.0")
public class SpeedByRoadCategory {
  public static final String JSON_PROPERTY_MINIMUM_SPEED = "minimumSpeed";
  private Integer minimumSpeed;

  public static final String JSON_PROPERTY_MAXIMUM_SPEED = "maximumSpeed";
  private Integer maximumSpeed;

  public SpeedByRoadCategory() { 
  }

  public SpeedByRoadCategory minimumSpeed(Integer minimumSpeed) {
    this.minimumSpeed = minimumSpeed;
    return this;
  }

  /**
   * The minimum speed of the vehicle [km/h] for roads of this road category. Must be less or equal to the maximum speed.
   * minimum: 1
   * maximum: 255
   * @return minimumSpeed
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MINIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getMinimumSpeed() {
    return minimumSpeed;
  }


  @JsonProperty(JSON_PROPERTY_MINIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinimumSpeed(Integer minimumSpeed) {
    this.minimumSpeed = minimumSpeed;
  }


  public SpeedByRoadCategory maximumSpeed(Integer maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
    return this;
  }

  /**
   * The maximum speed of the vehicle [km/h] for roads of this road category. Must be greater or equal to the minimum speed.
   * minimum: 1
   * maximum: 255
   * @return maximumSpeed
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAXIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getMaximumSpeed() {
    return maximumSpeed;
  }


  @JsonProperty(JSON_PROPERTY_MAXIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaximumSpeed(Integer maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
  }


  /**
   * Return true if this SpeedByRoadCategory object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpeedByRoadCategory speedByRoadCategory = (SpeedByRoadCategory) o;
    return Objects.equals(this.minimumSpeed, speedByRoadCategory.minimumSpeed) &&
        Objects.equals(this.maximumSpeed, speedByRoadCategory.maximumSpeed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minimumSpeed, maximumSpeed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpeedByRoadCategory {\n");
    sb.append("    minimumSpeed: ").append(toIndentedString(minimumSpeed)).append("\n");
    sb.append("    maximumSpeed: ").append(toIndentedString(maximumSpeed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `minimumSpeed` to the URL query string
    if (getMinimumSpeed() != null) {
      joiner.add(String.format("%sminimumSpeed%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMinimumSpeed()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `maximumSpeed` to the URL query string
    if (getMaximumSpeed() != null) {
      joiner.add(String.format("%smaximumSpeed%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMaximumSpeed()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

